title: HANG ZHAO
url: "https://hsparrow.github.io"
# baseurl: "/index"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/index"
 - name: "Blog"
   link: "/blog"
 - name: "Projects"
   link: "/projects/hang_resume.pdf"
 - name: "Resume"
   link: "/files/hang_resume.pdf"