title: Mind Funk
# baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/personal-website/"
 - name: "Blog"
   link: "/_posts/"
 - name: "Projects"
   link: "/projects/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"